#邮箱配置
spring:
  mail:
    host: smtp.qq.com
    from: 522425561@qq.com
    # 使用自己的 QQ 邮箱地址 + SMTP 授权码填充
    username: 522425561@qq.com
    password: yrkuzqmrieehbiid
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
alarm:
  # 接收报警的用户邮箱，多个人时，使用英文逗号分隔
  user: your_qq@qq.com
